import Head from "next/head";

import About from "@/components/About";
import BlogList from "@/components/BlogList";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import HowItWorks from "@/components/HowItWorks";
import LearningPath from "@/components/LearningPath";
import MidBanner from "@/components/MidBanner";
import Podcast from "@/components/Podcast";
import Reviews from "@/components/Reviews";

export default function Home() {
  return (
    <>
      <Head>
        <title>BLOCKHACK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white bg-black">
        <Hero />
        <LearningPath />
        <HowItWorks />
        <MidBanner />
        <BlogList />
        <Podcast />
        <Reviews />
        <About />
      </main>

      <Footer />
    </>
  );
}
