import {
  BitcoinBoxIllustration,
  BitcoinToEthereumIllustration,
  CubeIllustration,
  DEFIIllustration,
  EtherBoxIllustration,
  MetaverseIllustration,
  NFTIllustration,
  RollupsIllustration,
  Web3AndBlockchainIllustration,
} from "@/ui/illustrations";
import { StarIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import Link from "next/link";
const Course = () => {
  return (
    <>
      <Head>
        <title>Courses - BLOCKHACK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white bg-black">
        {/* hero */}
        <section className="grid h-screen bg-secondary-500 place-items-center">
          <h1 className="font-display text-8xl md:text-[16em]">Courses</h1>

          <CubeIllustration className="absolute w-20 left-[35%] top-[55%] hidden md:block" />
          <BitcoinBoxIllustration className="absolute w-28 left-[44%] top-[30%] hidden md:block" />
          <EtherBoxIllustration className="absolute w-32 left-[60%] top-[50%] hidden md:block" />
        </section>

        <section className="min-h-screen bg-black rounded-t-[4em] grid md:grid-cols-[20%,1fr] -mt-[4em]">
          <article></article>

          {/* all courses */}
          <article className="px-4 py-16 space-y-10 md:px-16 md:py-16">
            {/* card one */}
            <article className="grid p-6 text-black md:grid-cols-2 bg-primary-500 rounded-3xl">
              <div className="flex flex-col justify-center">
                <h2 className="text-secondary-500 text-6xl md:text-[8em] font-display leading-none">
                  Web3 and Blockchain
                </h2>
                <p className="my-4 font-semibold w-[80%]">
                  Master the fundamentals of blockchain technology and Web3.
                  Grasp core concepts, consensus mechanisms, and smart
                  contracts, paving the way for advanced understanding and
                  applications.
                </p>

                <Link
                  href="/course/web3-and-blockchain"
                  className="block mt-2 text-3xl underline uppercase font-display"
                >
                  Learn More
                </Link>
              </div>

              <div className="flex flex-col items-end text-right">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-2xl font-semibold">4,8</p>

                    <div className="inline-flex items-center space-x-1">
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                    </div>
                  </div>

                  <h3 className="text-xl text-gray-500">49 feedback</h3>
                </div>

                <Web3AndBlockchainIllustration className="w-full md:w-96 md:mr-8" />
              </div>
            </article>

            {/* card two */}
            <article className="grid p-6 text-white bg-black border md:grid-cols-2 rounded-3xl">
              <div className="flex flex-col justify-center">
                <h2 className="text-secondary-500 text-6xl md:text-[8em] font-display leading-none">
                  Layer 2’s
                </h2>
                <p className="my-4 font-semibold w-[80%]">
                  This course plan provides a comprehensive framework for
                  mastering Layer 2 solutions, covering their fundamentals,
                  technologies, platforms, applications, development,
                  tokenomics, governance, risk management, future developments,
                  and practical integration.
                </p>

                <Link
                  href="/course/layer-2"
                  className="block mt-2 text-3xl underline uppercase font-display"
                >
                  Learn More
                </Link>
              </div>

              <div className="flex flex-col items-end text-right">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-2xl font-semibold">4,9</p>

                    <div className="inline-flex items-center space-x-1">
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                    </div>
                  </div>

                  <h3 className="text-xl text-gray-500">21 feedback</h3>
                </div>

                <BitcoinToEthereumIllustration className="w-full md:mr-8" />
              </div>
            </article>

            {/* card three */}
            <article className="grid p-6 text-white border md:grid-cols-2 bg-secondary-500 rounded-3xl">
              <div className="flex flex-col justify-center">
                <h2 className="text-primary-500 text-6xl md:text-[8em] font-display leading-none">
                  DeFi
                </h2>
                <p className="my-4 font-semibold w-[80%]">
                  Explore decentralized finance, its core concepts, and
                  applications. Learn how to leverage DeFi protocols to manage
                  digital assets, earn passive income, and understand emerging
                  trends.
                </p>

                <Link
                  href="/course/defi"
                  className="block mt-2 text-3xl underline uppercase font-display"
                >
                  Learn More
                </Link>
              </div>

              <div className="flex flex-col items-end text-right">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-2xl font-semibold">4,9</p>

                    <div className="inline-flex items-center space-x-1">
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                    </div>
                  </div>

                  <h3 className="text-xl text-gray-300">60 feedback</h3>
                </div>

                <DEFIIllustration className="w-full md:w-96 md:mr-8" />
              </div>
            </article>

            {/* card four */}
            <article className="grid p-6 text-black md:grid-cols-2 bg-primary-500 rounded-3xl">
              <div className="flex flex-col justify-center">
                <h2 className="text-secondary-500 text-6xl md:text-[8em] font-display leading-none">
                  Rollups
                </h2>
                <p className="my-4 font-semibold w-[80%]">
                  This course plan provides a comprehensive framework for
                  mastering Rollups, covering their fundamentals, types,
                  platforms, applications, development, tokenomics, governance,
                  risk management, future developments, and practical
                  integration.
                </p>

                <Link
                  href="/course/rollups"
                  className="block mt-2 text-3xl underline uppercase font-display"
                >
                  Learn More
                </Link>
              </div>

              <div className="flex flex-col items-end text-right">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-2xl font-semibold">4,8</p>

                    <div className="inline-flex items-center space-x-1">
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                      <StarIcon className="w-6 h-6 text-secondary-500" />
                    </div>
                  </div>

                  <h3 className="text-xl text-gray-500">49 feedback</h3>
                </div>

                <RollupsIllustration className="w-full md:mr-8" />
              </div>
            </article>

            {/* card five */}
            <article className="grid p-6 text-white bg-black border md:grid-cols-2 rounded-3xl">
              <div className="flex flex-col justify-center">
                <h2 className="text-secondary-500 text-6xl md:text-[8em] font-display leading-none">
                  NFTs
                </h2>
                <p className="my-4 font-semibold w-[80%]">
                  Uncover the world of non-fungible tokens, their creation, and
                  use cases. Learn how to mint, buy, sell, and utilize NFTs in
                  various industries, including gaming, art, and collectibles.
                </p>

                <Link
                  href="/course/nft"
                  className="block mt-2 text-3xl underline uppercase font-display"
                >
                  Learn More
                </Link>
              </div>

              <div className="flex flex-col items-end text-right">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-2xl font-semibold">4,9</p>

                    <div className="inline-flex items-center space-x-1">
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                    </div>
                  </div>

                  <h3 className="text-xl text-gray-500">21 feedback</h3>
                </div>

                <NFTIllustration className="w-full md:mr-8" />
              </div>
            </article>

            {/* card six */}
            <article className="grid p-6 text-white border md:grid-cols-2 bg-secondary-500 rounded-3xl">
              <div className="flex flex-col justify-center">
                <h2 className="text-primary-500 text-6xl md:text-[8em] font-display leading-none">
                  Metaverse
                </h2>
                <p className="my-4 font-semibold w-[80%]">
                  Delve into the world of virtual reality and blockchain. Study
                  the emergence, growth, and implications of metaverse
                  platforms, digital assets, and communities while discovering
                  new opportunities.
                </p>

                <Link
                  href="/course/metaverse"
                  className="block mt-2 text-3xl underline uppercase font-display"
                >
                  Learn More
                </Link>
              </div>

              <div className="flex flex-col items-end text-right">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-2xl font-semibold">4,9</p>

                    <div className="inline-flex items-center space-x-1">
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                      <StarIcon className="w-6 h-6 text-primary-500" />
                    </div>
                  </div>

                  <h3 className="text-xl text-gray-300">60 feedback</h3>
                </div>

                <MetaverseIllustration className="w-full md:w-96 md:mr-8" />
              </div>
            </article>
          </article>
        </section>
      </main>
    </>
  );
};

export default Course;
